### ISSUE TITLE
Adding priority to a constraint

### ISSUE THREAD

**Issue by ben95beng** [smileyborg/PureLayout#37]
- Is there a way to add explicit priority to a particular constraint before installing it?
- I tried using [UIView autoSetPriority:forConstraints:] before setting constraints with no success. 
- Using ios framework, I understand that it's possible to setup constraint and change its priority and then install it. Is there a way, in PureLayout, to create the constraint without installing it? Or can we remove the constraint temporarily to change it's priority?
- In particular, I want to add two similar constraints that differ only in 'relation' value to a view. And I need to give the constraints different priority.

**Comment by smileyborg** [comment]
Yes, there is an example of using the block-based `autoSetPriority:forConstraints:` method in the example project, [Demo 6](https://github.com/smileyborg/PureLayout/blob/master/Example/Example-iOS/Demos/ALiOSDemo6ViewController.m#L48). This API will work as long as the constraints you intend to change the priority on are created using PureLayout (if you use Apple's SDK API directly, it won't affect those constraints).

You are correct that you cannot change the priority of installed/activated constraints. So you should either use the above block-based API to apply a priority to one or more constraints, or you can use the `+[UIView autoCreateConstraintsWithoutInstalling:]` API to create the constraints only (see example in [Demo 10](https://github.com/smileyborg/PureLayout/blob/master/Example/Example-iOS/Demos/ALiOSDemo10ViewController.m#L52)), at which point you can manually set a priority.

If you can avoid it, you should not create constraints that are automatically installed/activated, then remove them just to change the priority, then re-add them. This will lead to poor performance, as installing and removing constraints can be computationally expensive.

Let me know if that isn't clear, or if you are still having trouble getting it to work.

**Comment by ben95beng** [comment]
Thanks,
I think `<+[UIView autoCreateConstraintsWithoutInstalling:]>` may be what I need. I will try it.

**Comment by alanscarpa** [comment]
@smileyborg Just a heads up - the links in your answer are broken :(  And this answer is first for "constraint priority purelayout "
