### ISSUE TITLE
purelayout 2.0.x not support xcode 5.0.2

### ISSUE THREAD

**Issue by wingyiu** [smileyborg/PureLayout#39]
when i try to build my project using xcode 5.0.2 , sdk ios 7, yosemite,  i got so many errors

```
/Users/user/xxx/Pods/PureLayout/Source/PureLayoutDefines.h:140:24: Use of undeclared identifier 'NSLayoutAttributeTrailingMargin'; did you mean 'NSLayoutAttributeTrailing'?
```

**Comment by smileyborg** [comment]
PureLayout should fully support Xcode 5.1 and 6, and iOS 6 - 8. `PureLayoutDefines.h` defines and uses a number of preprocessor macros to conditionally compile code that requires the iOS 8 SDK (which is unavailable in Xcode 5). I haven't tested using Xcode 5.0.2 though, so perhaps you could try Xcode 5.1?

I don't know what might be the issue, so please try and investigate why the macros like `__PureLayout_MinBaseSDK_iOS_8_0` are not working and let me know if you can identify a problem.

**Comment by smileyborg** [comment]
Closing until further information is provided.
