### ISSUE TITLE
autoDistributeViewsAlongAxis not working on device

### ISSUE THREAD

**Issue by darkoromanov** [smileyborg/PureLayout#43]
Hi, I'm using this code

    [views autoMatchViewsDimension:ALDimensionHeight];
    [views autoDistributeViewsAlongAxis:ALAxisHorizontal alignedTo:ALAttributeHorizontal withFixedSpacing:10.0f];

to align a dynamic number of buttons inside a UIView. It works with all the simulated devices but not on real devices (tested: iPhone4, iPhone4S).

**Comment by smileyborg** [comment]
Hi Darko, can you provide some more information on what's happening so I can help you debug the issue? Perhaps you can share an example project that demonstrates the issue you're seeing, or modify one of the demos in the PureLayout Example project to do so?

I haven't seen any issues with this myself, nor have I seen any reports of this, so it's likely something specific to your configuration (not an issue with PureLayout itself).

**Comment by darkoromanov** [comment]
It won't be easy as I'm really hurry but I'll try to do it!

**Comment by smileyborg** [comment]
Closing this issue for now due to lack of info. Please provide more info or an example project as requested and this can be reopened.

**Comment by darkoromanov** [comment]
Yeah, I'm sorry about it. I'll be back on that problem next week, I'll open the issue in case.
