### ISSUE TITLE
how to vetical align center in viewcontroller?

### ISSUE THREAD

**Issue by phaibin** [smileyborg/PureLayout#44]
Now I can use autoAlignAxisToSuperviewAxis:ALAxisHorizontal to vertical align center in superview. But how to vertical align center in viewcontroller? That is, vertical align center in remaining area besides navigation bar.
Thanks!

**Comment by smileyborg** [comment]
Hi Leon,

Good question. My recommendation is to use a container view that is a subview of the view controller's view. Here's how you'd do that:

1. Create a container view and add it as a subview to the view controller's view
2. Pin the container view to the left & right edges of its superview
3. Pin the container view to the top & bottom layout guides of the view controller

At this point, your container view will always be sized to completely fill the visible area of the screen without going underneath the navigation bar or toolbar. So the final steps:

4. Add your view as a subview of the container view, then tell it to align or center in its superview as desired

Hope that makes sense! Good luck :)

**Comment by phaibin** [comment]
Thank you! Very good advice!

**Comment by marcus30** [comment]
Thanks!

**Comment by yangzheng006** [comment]
Thanks
