### ISSUE TITLE
Carthage install fails due to header naming

### ISSUE THREAD

**Issue by adly-holler** [smileyborg/PureLayout#46]
If you use the latest Carthage and try to import PureLayout into your app, Xcode will fail to build the module, because the `Modules/module.modulemap` file points to `PureLayout_iOS.h` as the framework header, but the framework header is actually `PureLayout.h`. Currently thinking of the cleanest way to fix this.

**Comment by smileyborg** [comment]
Hey Adly,

When you build one of the dynamic frameworks for PureLayout, the framework header is actually `<PureLayout_iOS/PureLayout_iOS.h>` (substitute `_Mac` for the OS X version). That framework header then imports `PureLayout.h`, which is simply an umbrella/convenience header itself.

I see the problem you describe though. It's a simple fix -- the framework headers were not marked as Public in the Xcode project, which was causing them to not be included in the built framework's headers. Making them Public resolves the issue, so you can now use `@import PureLayout_iOS`.

**Comment by smileyborg** [comment]
Thanks for bringing this up! I clearly forgot to test the final stage of integration after a whole bunch of changes yesterday :)
