### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by smileyborg** [smileyborg/PureLayout#51]
* [x] Add setup instructions for Swift (e.g. bridging header)
* [x] Add some sample code to README (Swift & Objective-C) so casual readers get a feel for the syntax
* [x] Add links to Swift sample project
* [x] Put setup instructions at top above cheat sheet
* [x] Add a "table of contents" with links to sections of the README

**Comment by danie11am** [comment]
Hi there - great work. Just one comment on README, "Import the PureLayout.h umbrella header.
Swift: import PureLayout " seems incorrect as I found that I didn't need to have `import PureLayout` in the classes that use PureLayout. It would give me an error if I do that. I just need to have `#import "PureLayout.h"` in bridging header.

**Comment by smileyborg** [comment]
Hi Daniel,

Which integration method are you using? If you are using CocoaPods or Carthage, then you should not need to add PureLayout to your bridging header, and just need to `import PureLayout` from your Swift code.

If you are manually integrating the PureLayout source code into your project, then you do need to import the `PureLayout.h` header directly from your bridging header (assuming you've integrated PureLayout into the same target that you wish to use it from).

**Comment by danie11am** [comment]
Hi Tyler,

I'm using CocaoPods but I didn't put the "use_frameworks" option. I guess that's why I'm seeing different behaviour?

My Podfile only has one line `pod 'PureLayout'`. I'm using CocoaPods 0.36.4. In this project I found that I don't need to add `import PureLayout` and can use PureLayout in all my swift files, but I need to setup the bridging header.

**Comment by smileyborg** [comment]
Oh! Yeah, that's right - if you're using CocoaPods without `use_frameworks!` then you would need to import it this way. So many possibilities :) I'll update the README again tomorrow, thanks!

**Comment by smileyborg** [comment]
@danie11am Clarified this in 01425aa5fe328faf2f77ed8d008d79442ddacb37 - let me know what you think!

**Comment by danie11am** [comment]
Cool! I think it looks good. I don't know about Carthage but I'm sure you do. ; ]
