### ISSUE TITLE
align centerlines of two views

### ISSUE THREAD

**Issue by pukeanddie** [smileyborg/PureLayout#52]
I know this has to be possible, and I must just be missing this in the api documentation, but nonetheless I cannot figure this out using purelayout. I want viewA to align it's centerline to viewB.

**Comment by smileyborg** [comment]
Hi Nat,

Take a look at the [`-[UIView autoAlignAxis:toSameAxisOfView:]`](https://github.com/smileyborg/PureLayout/blob/master/PureLayout/PureLayout/ALView%2BPureLayout.h#L143) API. It should do exactly what you need.

Let me know if you have any other questions!

**Comment by pukeanddie** [comment]
I'd definitely tried that.. with no effect, but i will revisit. Perhaps
something else was amiss. Thank you.

**Comment by smileyborg** [comment]
Make sure you aren't getting the axes mixed up -- you can reference [this illustration](https://github.com/smileyborg/PureLayout/blob/master/Images/PureLayout-CommonAttributes.png) if they aren't clear.
