### ISSUE TITLE
not compiling on OS X 10.7

### ISSUE THREAD

**Issue by azplanlos** [smileyborg/PureLayout#58]
unfortunately the latest master is not building on OS X 10.7 due to unrecognized selectors and properties:

    NSArray+PureLayout.m:58:13: No known class method for selector 'activateConstraints:' 
    NSArray+PureLayout.m:78:9: No known class method for selector 'deactivateConstraints:'
    NSLayoutConstraint+PureLayout.m:52:18: Property 'active' not found on object of type   'NSLayoutConstraint *'
    NSLayoutConstraint+PureLayout.m:119:14: Property 'identifier' not found on object of type 'NSLayoutConstraint *'

Is there any chance to fix this?

Thanks!

**Comment by smileyborg** [comment]
Hey Andreas,

Thank you for bringing this up! I don't actually have a machine with OS X 10.7 around to test this, but I think I fixed the issue in master. Can you please try the latest code and tell me how it goes?

If it's working correctly now I will push an update to the pod ASAP.

Thanks!

**Comment by smileyborg** [comment]
@azplanlos Any updates on this? I'd like to publish an update to the pod if it is fixed for you.

**Comment by smileyborg** [comment]
@azplanlos I would greatly appreciate an update from you, but since I have not heard back in over 2 weeks, I am closing this issue and will assume it has been fixed.
