### ISSUE TITLE
New feature: DSL 

### ISSUE THREAD

**Issue by raygun101** [smileyborg/PureLayout#63]
Have you seen: https://github.com/SnapKit/SnapKit I like the DSL approach.

**Comment by smileyborg** [comment]
Hi Leslie,

Yes, I have seen SnapKit -- it is a pure Swift port of the [Masonry](https://github.com/SnapKit/Masonry) project (it used to be named "Snappy", then "Snap", and finally "SnapKit").

Personally, I am a fan of [Cartography](https://github.com/robb/Cartography) for pure-Swift environments, as I think it has the cleanest and most expressive syntax, and really leverages some of the capabilities of Swift.

If you are working in pure Swift, by all means do consider using one of these options. PureLayout is designed differently -- it is an Objective-C library that closely follows Apple's SDK conventions and style. The same codebase/library works great in Objective-C as well as in Swift, making it more flexible than pure Swift libraries that can only be used in Swift.

PureLayout is definitely not going to have a DSL, there are plenty of other great libraries already available for that.

Let me know if you have a specific question that I did not address.
