### ISSUE TITLE
Use PureLayout on TableView.tableHeaderView lead to Crash, iPhone4s iOS7.1.2

### ISSUE THREAD

**Issue by swplzj** [smileyborg/PureLayout#65]
Use PureLayout on TableView.tableHeaderView lead to Crash, iPhone4s iOS7.1.2
How to handle, Thank you.

**Comment by smileyborg** [comment]
Hi @swplzj,

This is almost certainly not related to PureLayout. If I had to guess, you're running into a general auto layout constraint exception, or some other UIKit related issue.

Anyways, if you would like help debugging this, you will need to provide more details -- in particular, the exception message and backtrace, and potentially a sample project to reproduce the issue.
