### ISSUE TITLE
Using PureLayout library pinEdge right UIView in UIScrollView not working or how-to?

### ISSUE THREAD

**Issue by mixdesign** [smileyborg/PureLayout#66]
Hi @smileyborg . Would you look at this issue:<br>http://stackoverflow.com/questions/30296087/using-purelayout-library-pinedge-right-uiview-in-uiscrollview-not-working-or-how

**Comment by smileyborg** [comment]
Hi Almas,

Please take a look at this comment on a similar question: https://github.com/smileyborg/PureLayout/issues/61#issuecomment-93819808

Put simply, auto layout works differently inside UIScrollView. This has nothing to do with PureLayout, it's just a general auto layout concept. Apple's Technical Note linked in the above comment has more details.
