### ISSUE TITLE
Enhancements for iOS 9 & OS X El Capitan

### ISSUE THREAD

**Issue by smileyborg** [smileyborg/PureLayout#69]
There are some new Auto Layout APIs and related changes introduced with iOS 9 and OS X El Capitan that PureLayout will want to take advantage of.

Exact details are still TBD, but here are some links to changes of interest:

* [NSLayoutAnchor](https://developer.apple.com/library/prerelease/ios/documentation/AppKit/Reference/NSLayoutAnchor_ClassReference/index.html)
  * Related new APIs on [UIView](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIView_Class/index.html#//apple_ref/doc/uid/TP40006816-CH3-DontLinkElementID_29)/[NSView](https://developer.apple.com/library/prerelease/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSView_Class/index.html#//apple_ref/doc/uid/20000014-SW71)
* [UILayoutGuide](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UILayoutGuide_Class_Reference/index.html) and [NSLayoutGuide](https://developer.apple.com/library/prerelease/mac/documentation/AppKit/Reference/NSLayoutGuide_ClassReference/index.html)
  * Related new APIs on [UIView](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIView_Class/index.html#//apple_ref/doc/uid/TP40006816-CH3-DontLinkElementID_30)/[NSView](https://developer.apple.com/library/prerelease/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSView_Class/index.html#//apple_ref/doc/uid/20000014-SW210)
* [UIStackView](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIStackView_Class_Reference/index.html) (and existing OS X counterpart, [NSStackView](https://developer.apple.com/library/mac/documentation/AppKit/Reference/NSStackView_Class/index.html))

PureLayout will adopt new Objective-C syntax:

* Nullability annotations
* Generics

All the above changes will be made in a backwards-compatible fashion, both for compile time (older versions of Xcode) and runtime (maintaining the existing deployment targets).

Separately, for v3.0.0 the existing methods that were deprecated in v2.0.0 will be removed entirely.

### Current Status

* [x] Remove deprecated methods 6d20408
* [x] Nullability annotations for all headers b030f4f
* [x] Generics for public headers b030f4f
* [x] Generics in .m files bcd91bf
* [x] Add a new API to batch activate and return constraints. Similar to [this existing API](https://github.com/smileyborg/PureLayout/blob/b030f4f3289271a688d1f67a0fc8b43b675f6d2b/PureLayout/PureLayout/ALView%2BPureLayout.h#L58), but activates all the constraints before returning. c2bcb1f
* [x] Move class methods on UIView/NSView to NSLayoutConstraint 1583f7b
* [x] Investigate new SDK changes and potential impact
  * No direct impact -- the new APIs are complementary to PureLayout.

**Comment by ctava** [comment]
you should do this

**Comment by jkyin** [comment]
:+1:
