### ISSUE TITLE
Xcode 6 & Example-IOS

### ISSUE THREAD

**Issue by zivelli** [smileyborg/PureLayout#79]
@smileyborg , so is Xcode 6.4 no longer compatible with the Example Projects?

**Comment by smileyborg** [comment]
Hi @zivelli,

Xcode 6 should work fine with the example app, just make sure to build the scheme `Example-iOS`.

Please let me know if you see otherwise!

**Comment by zivelli** [comment]
Thnxs, I get Assertion Failure in -[ALiOSDemoListController displayDemoAtIndex:]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Class should not be nil!'

**Comment by smileyborg** [comment]
You're right! This is a bug, fixing it right now :)

**Comment by zivelli** [comment]
Thnxs man, couldn't figure out how to get around this bug. Look forward to the update!

**Comment by smileyborg** [comment]
OK, should be all fixed. Please give the latest a try!

**Comment by zivelli** [comment]
Awesome! I can confirm, works on my iPhone 5S and IOS Simulator - iphone 6 & 6+
Thnxs
