### ISSUE TITLE
Library not loaded error in storyboards

### ISSUE THREAD

**Issue by barnybug** [smileyborg/PureLayout#81]
Not exactly sure when I first started seeing this error, but it occurs opening storyboards that incorporate '@IBDesignable' classes in my project using PureLayout elsewhere (whether the classes themselves are using PureLayout or not).

file:///.../Main.storyboard: error: IB Designables: Failed to update auto layout status: dlopen(MyApp.app, 1): Library not loaded: @rpath/PureLayout.framework/PureLayout
  Referenced from: MyApp.app
  Reason: Incompatible library version: MyApp requires version 2.0.0 or later, but PureLayout provides version 1.0.0
file:///.../Main.storyboard: error: IB Designables: Failed to render instance of PaddedLabel: dlopen(MyApp.app, 1): Library not loaded: @rpath/PureLayout.framework/PureLayout
  Referenced from: MyApp.app
  Reason: Incompatible library version: ReallaApp requires version 2.0.0 or later, but PureLayout provides version 1.0.0

Installed using cocoapods.
The error is benign otherwise - app compiles, runs fine, but it'd be nice if there's a way to stop storyboard designer complaining.

**Comment by smileyborg** [comment]
Hi Barnaby,

Thanks for bringing this up! This is interesting -- I have not tried using `@IBDesignable` much myself. A few quick questions:

1. This is not related to the recent v3.0.0 release, right? This was happening with v2.x (before yesterday)?
1. Is your codebase in Swift or Objective-C?

If you are able to share any sample project that demonstrates this issue, that would be very helpful! Otherwise I can try to reproduce it myself.

**Comment by barnybug** [comment]
Hi,

1. no, it's not related to a recent release.
2. Swift codebase

I tried setting up an example sample project from clean, and sure enough this works perfectly without complaint! So it must be something we're doing in application itself that's causing this - sorry I doubt this issue is much use without a reproduction case, so feel free to close..

**Comment by smileyborg** [comment]
OK, thanks for checking on this. I found this issue on CocoaPods, perhaps take a look here and see if you find anything interesting here: https://github.com/CocoaPods/CocoaPods/issues/3903

It definitely seems to be some sort of Xcode and/or CocoaPods issue, not anything specific to PureLayout.
