### ISSUE TITLE
Question about PureLayout

### ISSUE THREAD

**Issue by goktugyil** [smileyborg/PureLayout#83]
Hello,

I couldn't understand the benefits of PureLayout, in comparison to manually setting up view sizes according to the screensize and generating the user interface in a hardcoded fashion. Could somebody explain why and when to use this?

**Comment by smileyborg** [comment]
Hi Goktug,

It sounds like you're asking why should you use Auto Layout (in general, not just PureLayout), versus calculating and setting the `frame` of views manually?

This question has been asked by many people and there are many different answers to this, for example:

* http://www.quora.com/Should-I-use-Auto-Layout
* http://stackoverflow.com/a/18745663/796419

In general, Auto Layout is far more powerful than the "springs & struts" (autoresizing mask) system it replaces. It allows you to specify your layout in a much more declarative fashion, that scales much better when you are supporting more than a couple fixed sizes.

You *could* do everything manually using frame math, but this will be a lot more difficult, especially in a world where you're supporting dozens of unique screen sizes, plus things like split-screen multitasking.

I would recommend watching some of the WWDC talks that introduce Auto Layout for more details.
