### ISSUE TITLE
Split-screen multitasking on iOS 9

### ISSUE THREAD

**Issue by jyounus** [smileyborg/PureLayout#87]
Hey there,

I've been using auto-layout with storyboard in the past, but I started to realise that it's quite limiting/becomes more of a burden when it comes to complex designs. I've been looking at alternatives, even if that means doing more in code, rather than the easy "drag and drop" storyboard way of constraining UI elements.

My question is, would the new iOS 9 split-screen multitasking feature work just fine if I used PureLayout instead of auto-layout directly via storyboard? I don't see any reason why not, since (as far as I understand it) PureLayout is just a wrapper for auto-layout. But I just wanted to confirm it.

Thanks in advance! :)

**Comment by smileyborg** [comment]
Hi Junaid,

Yes, you can implement support for split-screen multitasking very well using PureLayout. PureLayout just makes creating & managing auto layout constraints easier. But they are the same constraints you'd get if you used Interface Builder instead.

I gave a talk earlier this year, [Adaptive Auto Layout](https://www.youtube.com/watch?v=taWaW2GzfCI), which talks about lots of things you will want to be aware of when building your app to support adaptivity. I highly recommend watching the YouTube video there if you're interested in learning more, including some specific discussion about PureLayout as well.

If you don't have time to watch the video, make sure you understand how trait collections are inherited, and then implement `traitCollectionDidChange:` to set up and change your constraints at runtime, primarily based on the `horizontalSizeClass`.

**Comment by jyounus** [comment]
Will certainly watch the video. Thanks a lot for your help, appreciate it!

J
